language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
before_install:
  - sudo apt-get install -y curl
  - sudo apt-get update
  - sudo apt-get purge -y postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6
  - sudo apt-get upgrade -y openssl
  - sudo apt-get upgrade -y

# Load some dummy data for testing.
before_script:
  - chmod +x ./dummydata.sh
  - ./dummydata.sh
