language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
before_install:
  - sudo apt-get install -y curl
  - sudo apt-get update

# Load some dummy data for testing.
before_script:
  - chmod +x ./dummydata.sh
  - ./dummydata.sh

# Test the binary. TODO: Should become integrated in a better way.
after_script:
  - cargo install
  - nordselect
  - nordselect za standard
  - nordselect us p2p
  - nordselect de dedicated
  - nordselect se tor
  - nordselect ee obfuscated
  - nordselect nl double
  - nordselect -h
  - nordselect --list-filters
  - sudo setcap cap_net_raw+ep "/home/travis/.cargo/bin/nordselect"
  - nordselect -p be
  - nords